FORMAT: 1A
HOST:https://mehedyalhasan.herokuapp/allstudent

# Mehedy302 

 Students information
## Questions Collection [/getstudents]

### List All students [GET]

+ Response 200 (application/json)
 [
    {
        "_id": "5cc87399cb52980004a873ba",
        "name": "Mehedy",
        "id": "1610476124",
        "dept": "cse"
    },
    {
        "_id": "5cc8783ec152a00004515312",
        "name": "Anichur",
        "id": "1610476125",
        "dept": "cse"
    }
]




### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }