FORMAT: 1A
HOST:https://mehedyalhasan.herokuapp/allstudent

# Mehedy302 

 Students information
## Students Collection [/getstudents]

### List All students [GET]

+ Response 200 (application/json)
 [
    {
        "_id": "5cc87399cb52980004a873ba",
        "name": "Mehedy",
        "id": "1610476124",
        "dept": "cse"
    },
    {
        "_id": "5cc8783ec152a00004515312",
        "name": "Anichur",
        "id": "1610476125",
        "dept": "cse"
    }
]

collect student using id

## single student [/5cc87399cb52980004a873ba]
### Select a single student

+ Response 200 (application/json)
{
    "_id": "5cc87399cb52980004a873ba",
    "name": "Mehedy",
    "id": "1610476124",
    "dept": "cse"
}



## Creating a new student[/setstudent]
### Create a New student [POST]

 + Request (application/json)

        {   "name":"Anichur",
            "id":"1610476125",
            "dept":"cse"
        }

+ Response 201 (application/json)

    + Headers

            Location: /setstudent

    + Body

           {
                 "_id": "5cc885acb754d900040b0377",
                "name": "Anichur",
                "id": "1610476125",
                "dept": "cse"
        }



## Updating a  student[/5cc885acb754d900040b0377]
### update  a  student [PUT]

+ Request (application/json)

    {   
        "name": "Anisur",
        "id": "1610476125",
        "dept": "cse"
    }

+ Response empty (application/json)

 {
        "_id": "5cc885acb754d900040b0377",
        "name": "Anisur",
        "id": "1610476125",
        "dept": "cse"
    }
    
    
    
## Deleting a  student[/5cc885acb754d900040b0377]
### Delete  a  student [DELETE]

 

+ Response empty (application/json)